"""init2

Revision ID: 88d56915eedc
Revises: 9b007df0a4cb
Create Date: 2024-03-21 14:26:31.418802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d56915eedc'
down_revision: Union[str, None] = '9b007df0a4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_photo_blob', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_photo_blob')
    # ### end Alembic commands ###
