"""init2

Revision ID: aa2468b11992
Revises: 88d56915eedc
Create Date: 2024-03-21 14:28:38.287588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2468b11992'
down_revision: Union[str, None] = '88d56915eedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_photo_blob', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_photo_blob')
    # ### end Alembic commands ###
