"""init2

Revision ID: f90ab07dba67
Revises: aa2468b11992
Create Date: 2024-03-21 14:29:30.026556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90ab07dba67'
down_revision: Union[str, None] = 'aa2468b11992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_photo_blob', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_photo_blob')
    # ### end Alembic commands ###
